new_cmdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from new_cmdb.settings import STATIC_ROOT
from django.views.static import serve
from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$',serve,{"document_root":STATIC_ROOT}),
    url(r'',include('web.urls')),
]

handler404 = page_not_found
handler500 = page_error

web/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/4/23 下午1:46
# @Author  : 大兵



from django.conf.urls import url
from django.views.generic import TemplateView
from web.views import ServerView,ServerDetailView,AddServerView,AccountView,\
    DomainView,ConnectView,ServerEditView,UpdateDataView,AddAccountView,AccountEditView,\
    LoginView,IndexView,AddDomainView,EditDomainView,AddConnectView,EditConnectView,Lgout

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    # 登录
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'index/$', IndexView.as_view(), name='index'),
    url(r'lgout/$', Lgout.as_view(), name='lgout'),

    # 服务器
    url(r'^server/$',ServerView.as_view(),name='server'),
    url(r'^server-detail/(?P<id>\d+)$',ServerDetailView.as_view(),name='server-detail'),
    url(r'^edit-server/(?P<idd>\d+)$',ServerEditView.as_view(),name='server-edit'),
    url(r'^add-server/$',AddServerView.as_view(),name='add-server'),

    # 账号
    url(r'^account/$',AccountView.as_view(),name='account'),
    url(r'^add-account/$',AddAccountView.as_view(),name='add-account'),
    url(r'^edit-account/(?P<id>\d+)$',AccountEditView.as_view(),name='account-edit'),

    # 域名
    url(r'^domain/$',DomainView.as_view(),name='domain'),
    url(r'^add-domain/$',AddDomainView.as_view(),name='add-domain'),
    url(r'^edit-domain/(?P<id>\d+)$',EditDomainView.as_view(),name='domain-edit'),

    # 联系人管理
    url(r'^connect/$',ConnectView.as_view(),name='connect'),
    url(r'^add-connect/$',AddConnectView.as_view(),name='add-connect'),
    url(r'^edit-connect/(?P<id>\d+)$',EditConnectView.as_view(),name='connect-edit'),


    # 更新数据
    url(r'^update/$',UpdateDataView.as_view(),name="update_data")
]

repository/models.py
from datetime import datetime
from django.db import models

# 用户信息
class UserProfile(models.Model):
    name = models.CharField(u'姓名', max_length=32)
    email = models.EmailField(u'邮箱')
    phone = models.CharField(u'座机', max_length=32)
    mobile = models.CharField(u'手机', max_length=32)

    class Meta:
        verbose_name_plural = "用户表"

    def __str__(self):
        return self.name


# 服务器信息
class Server(models.Model):
    day_choices = (
        ("0",0),("1", 1), ("2", 2),("3", 3),("4", 4), ("5", 5), ("6", 6),
        ("7", 7), ("8", 8), ("9", 9), ("10", 10), ("11", 11), ("12", 12), ("13", 13), ("14", 14), ("15", 15),
        ("16", 16), ("17", 17), ("18", 18), ("19", 19), ("20", 20), ("21", 21), ("22", 22), ("23", 23),
        ("24", 24), ("25", 25), ("26", 26), ("27", 27), ("28", 28), ("29", 29), ("30", 30), ("31", 31)
    )
    env_choices = (
        ("test","测试环境"),
        ("prod","生产环境"),
        ("preprod","预生产环境"),
        ("base","基础环境"),
    )
    update_choices = (
        ("0", "未更新"),
        ("1", "已更新"),
        ("2", "更新失败"),
    )
    hostname = models.CharField(verbose_name="主机名",max_length=40,unique=True)
    remote_ip = models.CharField(verbose_name="远程连接IP",max_length=20)
    port = models.IntegerField(verbose_name="连接端口",default=22)
    self_ip = models.CharField(verbose_name="内网ip",max_length=200,blank=True,null=True)
    idc = models.ForeignKey("IDC",verbose_name="所属机房")
    team = models.ForeignKey("Team",verbose_name="所属业务线")
    account = models.ForeignKey("Account",verbose_name="所属账号",blank=True,null=True)
    username = models.CharField(verbose_name="用户名",default="root",max_length=20)
    password = models.CharField(verbose_name="密码",max_length=50)
    price = models.FloatField(verbose_name="价格",default=0)
    env_status = models.CharField(verbose_name="所属环境",choices=env_choices,max_length=20,default="测试")
    deadtime = models.IntegerField(choices=day_choices,default=0,verbose_name="到期时间")
    info = models.CharField(max_length=200, verbose_name="备注",blank=True,null=True)
    info_sercret = models.TextField(default="请输入密码信息", max_length=400, verbose_name="登陆密码信息",blank=True,null=True)
    assets = models.OneToOneField("Asset",verbose_name="资产信息",related_name="assets",blank=True,null=True)
    disk_info = models.ManyToManyField("Disk_info",verbose_name="硬盘信息",related_name="server_disk",blank=True)
    update_status = models.CharField(verbose_name="更新状态",choices=update_choices,max_length=40,default="未更新")

    class Meta:
        verbose_name_plural = "服务器表"

    def __str__(self):
        return self.hostname


# 资产信息
class Asset(models.Model):
    # 系统版本
    release = models.CharField(verbose_name="系统版本",max_length=50,blank=True,null=True)
    kernel_version = models.CharField(verbose_name="内核版本",max_length=50,blank=True,null=True)
    # cpu
    cpu_type = models.CharField(verbose_name="CPU型号",max_length=50,blank=True,null=True)
    cpu_nums = models.IntegerField(verbose_name="CPU个数",default=0)
    # 内存
    mem = models.CharField(verbose_name="内存",max_length=50,blank=True,null=True)
    swap = models.CharField(verbose_name="swap",max_length=50,blank=True,null=True)

    class Meta:
        verbose_name_plural = "资产表"

    def __str__(self):
        return self.release + "资产信息"


class Disk_info(models.Model):
    # 硬盘信息 名称与大小
    name = models.CharField(verbose_name="磁盘名称",max_length=10,blank=True,null=True)
    size = models.CharField(verbose_name="磁盘大小",max_length=50,blank=True,null=True)

    class Meta:
        verbose_name_plural = "硬盘信息"

    def __str__(self):
        return self.name + "硬盘信息"



# 业务线
class Team(models.Model):
    name = models.CharField(verbose_name="业务线名称",max_length=10)
    create_at = models.DateField(default=datetime.now().strftime('%Y-%m-%d'),verbose_name="创建时间")

    class Meta:
        verbose_name = "业务线表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 机房信息  含有物理机 阿里云
class IDC(models.Model):
    name = models.CharField(verbose_name="机房名称",max_length=10)
    romm_pos = models.CharField(verbose_name="机房位置",max_length=50,blank=True,null=True)
    cabinet_pos = models.CharField(verbose_name="机柜位置",max_length=50,blank=True,null=True)
    create_at = models.DateField(default=datetime.now().strftime('%Y-%m-%d'),verbose_name="创建时间")

    class Meta:
        verbose_name = "机房表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 资产变更记录



# 第三方账号  内部账号
class Account(models.Model):
    account_choices = (
        ("aly", "阿里云"),
        ("llht", "流量后台"),
        ("beian", "备案"),
        ("yxgl", "邮箱管理"),
        ("domian", "域名"),
        ("qyqq", "企业QQ"),
        ("dxpt", "短信平台"),
        ("internet", "网络"),
        ("other", "其他")
    )
    name = models.CharField(verbose_name="账号",max_length=50)
    password = models.CharField(verbose_name="密码",max_length=50)
    belong_to = models.CharField(max_length=50, default="阿里云", choices=account_choices, verbose_name="账号类别")
    url = models.URLField(verbose_name="登录地址",max_length=100)
    info = models.CharField(verbose_name="备注信息",max_length=200)


# 域名管理
class Domain(models.Model):
    name = models.CharField(max_length=50,verbose_name="域名")
    resolution = models.CharField(max_length=50,verbose_name="解析IP")
    account = models.ForeignKey(Account, verbose_name="所属账号")
    price = models.IntegerField(verbose_name="价格")
    datetime = models.DateField(default=datetime.now().strftime('%Y-%m-%d'),verbose_name="到期时间")
    info = models.CharField(max_length=200,verbose_name="备注")

    class Meta:
        verbose_name = "域名管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 联系人管理
class Connect(models.Model):
    name = models.CharField(max_length=50,verbose_name="姓名")
    mobile = models.CharField(max_length=20,verbose_name="手机号码",blank=True,null=True)
    tel = models.CharField(max_length=20,verbose_name="固定电话",blank=True,null=True)
    info = models.CharField(max_length=200,verbose_name="备注",blank=True,null=True)

    class Meta:
        verbose_name = "联系人管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/account.html
{% extends 'base.html' %}
{% block title %}
账号首页
{% endblock %}
{% block maincontent %}
    {% if tips %}
        <div class="notice_tips">{{ tips }}</div>
        {% block extra_js %}
            <script type="text/javascript">
                $(document).ready(function(){
                    t = setTimeout(function () {
                        $('.notice_tips').slideUp('slow');

                    },1500);
                    //location.href = "/server/";
                    //clearTimeout(t);
                })
            </script>
        {% endblock %}
    {% endif %}
    <div class="title">所在位置/账号首页</div>
			<div class="search_wrapper">
            <!-- 搜索框 -->
            <form action="{% url 'account' %}" method="get">
				<div class="search">
					<select name="category">
						<option value="all">所有账号</option>
						{% for i in account_choices %}
                            <option value="{{ i.0 }}" {% ifequal category i.0  %}selected{% endifequal %} >{{ i.1 }}</option>
                        {% endfor %}
					</select>
					<input type="text" name="keyword" {% ifnotequal keyword "all" %}value="{{ keyword }}"{% endifnotequal %} placeholder="请输入搜索关键字" />
                    <input type="submit" id="searchbtn" value="搜 索" />
					<a href="{% url 'add-account' %}"><input type="button" id="addbtn" value="添 加" /></a>
				</div>
            </form>
			</div>
			<!-- 数据表格 -->
			<div class="table_wrapper">
				<table class="table table-bordered table-hover">
					<thead>
						<tr><td width="50px">序号</td><td>账号</td><td>密码</td><td>账号类别</td><td>登录地址</td><td>备注</td><td width="120px;">操作</td></tr>
					</thead>
					<tbody>
                    {% for a in accounts.object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td><td>{{ a.name }}</td><td>{{ a.password }}</td><td>{{ a.get_belong_to_display }}</td>
                            <td><a target="_blank" href="{{ a.url }}">{{ a.url }}</a></td>
                            <td>{{ a.info }}</td>
                            <td><a href="{% url 'account-edit' a.id %}">编辑</a></td>
                        </tr>
                    {% endfor %}

					</tbody>
				</table>
			</div>
                共计 <b style="color: #d9534f">{{ count }}</b> 条数据。
			<!-- 页码 -->
			<div class="Page navigation mypage">
                <ul class="pagination">
                    {% if accounts.has_previous %}
                        <li><a href="?{{ accounts.previous_page_number.querystring }}">&lsaquo;&lsaquo;</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">&lsaquo;&lsaquo;</a></li>
                    {% endif %}
                    {% for page in accounts.pages %}
                        {% if page %}
                            {% ifequal page accounts.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page  }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}">{{ page  }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li><a href="#" class="none">...</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if accounts.has_next %}
                        <li><a href="?{{ accounts.next_page_number.querystring }}">&rsaquo;&rsaquo;</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">&rsaquo;&rsaquo;</a></li>
                    {% endif %}
                </ul>
            </div>
		</div>
{% endblock %}

templates/domain-add.html
{% extends 'base.html' %}
{% block title %}
域名编辑页
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="/static/js/bootstrap-datetimepicker.min.css" />
    <script src="/static/js/moment-with-locales.min.js" ></script>
    <script src="/static/js/bootstrap-datetimepicker.min.js" ></script>
{% endblock %}
{% block maincontent %}
    {% if err %}
        <div class="notice_tips">{{ err }}</div>
        {% block extra_js %}
        <script type="text/javascript">
            $(document).ready(function(){
                setTimeout(function () {
                    $('.notice_tips').slideUp('slow');
                },1500);
            });
        </script>
        <script>
            $(function () {
                $('#date_input').datetimepicker({
                format: 'YYYY-MM-DD',
                locale: moment.locale('zh-cn')
            });
            });
        </script>
    {% endblock %}
    {% endif %}
    <div class="title">所在位置/域名添加</div>
    <div class="detail_wrapper">
    <form action="{% url 'add-domain' %}" method="post" >
        <!-- 资产详情页 -->
        <div class="left">
            <ul class="list-unstyled">
                <li><span class="assets_title">域名:</span>
                    <input type="text" placeholder="请输入域名" name="d_name" value="{{ adddomain_form.d_name.value }}" /><br/>
                    {% if error.d_name %}<span class="error_tips">{{ error.d_name.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">解析地址:</span>
                    <input type="text" placeholder="请输入解析地址" name="resolution" value="{{ adddomain_form.resolution.value }}" /><br/>
                    {% if error.resolution %}<span class="error_tips">{{ error.resolution.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">所属账号:</span>
                    <select name="account">
                        {% for account in accounts %}
                            <option value="{{ account.id }}" {% if account.id|escape == adddomain_form.account.value %}selected{% endif %} >{{ account.name }}--{{ account.get_belong_to_display }}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><span class="assets_title">价格:</span>
                    <input type="text" placeholder="请输入价格" name="price" value="{{ adddomain_form.price.value }}" /><br/>
                    {% if error.price %}<span class="error_tips">{{ error.price.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">到期时间:</span>
                    <div class='col-sm-4' style="float: right;margin-right: -15px;">
                    <input type="text" placeholder="请选择日期" name="date" id="date_input" value="{{ adddomain_form.date.value }}" /><br/>
                    </div><br/>
                    {% if error.date %}<span class="error_tips">{{ error.date.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">备注:</span>
                    <textarea name="info" >{{ adddomain_form.info.value }}</textarea>
                </li>
            </ul>
        </div>
        <input id="edit_btn" value="保存" type="submit"  />
        <a href="{% url 'domain' %}"><div class="return_btn" >返回</div></a>
        {% csrf_token %}
    </form>
    </div>
{% endblock %}

templates/domain-edit.html
{% extends 'base.html' %}
{% block title %}
域名编辑页
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="/static/js/bootstrap-datetimepicker.min.css" />
    <script src="/static/js/moment-with-locales.min.js" ></script>
    <script src="/static/js/bootstrap-datetimepicker.min.js" ></script>
{% endblock %}
{% block maincontent %}
    {% if err %}
        <div class="notice_tips">{{ err }}</div>
        {% block extra_js %}
        <script type="text/javascript">
            $(document).ready(function(){
                setTimeout(function () {
                    $('.notice_tips').slideUp('slow');
                },1500);
            });
        </script>
        <script>
            $(function () {
                $('#date_input').datetimepicker({
                format: 'YYYY-MM-DD',
                locale: moment.locale('zh-cn')
            });
            });
        </script>
    {% endblock %}
    {% endif %}
    <div class="title">所在位置/域名添加</div>
    <div class="detail_wrapper">
    <form action="{% url 'domain-edit' d_info.id %}" method="post" >
        <!-- 资产详情页 -->
        <div class="left">
        {% if adddomain_form %}
            <ul class="list-unstyled">
                <li><span class="assets_title">域名:</span>
                    <input type="text" placeholder="请输入域名" name="d_name" readonly="readonly" value="{{ adddomain_form.d_name.value }}" /><br/>
                    {% if error.d_name %}<span class="error_tips">{{ error.d_name.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">解析地址:</span>
                    <input type="text" placeholder="请输入解析地址" name="resolution" value="{{ adddomain_form.resolution.value }}" /><br/>
                    {% if error.resolution %}<span class="error_tips">{{ error.resolution.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">所属账号:</span>
                    <select name="account">
                        {% for account in accounts %}
                            <option value="{{ account.id }}" {% if account.id|escape == adddomain_form.account.value %}selected{% endif %} >{{ account.name }}--{{ account.get_belong_to_display }}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><span class="assets_title">价格:</span>
                    <input type="text" placeholder="请输入价格" name="price" value="{{ adddomain_form.price.value }}" /><br/>
                    {% if error.price %}<span class="error_tips">{{ error.price.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">到期时间:</span>
                    <div class='col-sm-4' style="float: right;margin-right: -15px;">
                    <input type="text" placeholder="请选择日期" name="date" id="date_input" value="{{ adddomain_form.date.value }}" /><br/>
                    </div><br/>
                    {% if error.date %}<span class="error_tips">{{ error.date.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">备注:</span>
                    <textarea name="info" >{{ adddomain_form.info.value }}</textarea>
                </li>
            </ul>
        {% else %}
            <ul class="list-unstyled">
                <li><span class="assets_title">域名:</span>
                    <input type="text" placeholder="请输入域名" name="d_name" readonly="readonly" value="{{ d_info.name }}" /><br/>
                    {% if error.d_name %}<span class="error_tips">{{ error.d_name.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">解析地址:</span>
                    <input type="text" placeholder="请输入解析地址" name="resolution" value="{{ d_info.resolution }}" /><br/>
                    {% if error.resolution %}<span class="error_tips">{{ error.resolution.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">所属账号:</span>
                    <select name="account">
                        {% for account in accounts %}
                            <option value="{{ account.id }}" {% if account.id == d_info.account_id %}selected{% endif %} >{{ account.name }}--{{ account.get_belong_to_display }}</option>
                        {% endfor %}
                    </select>
                </li>
                <li><span class="assets_title">价格:</span>
                    <input type="text" placeholder="请输入价格" name="price" value="{{ d_info.price }}" /><br/>
                    {% if error.price %}<span class="error_tips">{{ error.price.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">到期时间:</span>
                    <div class='col-sm-4' style="float: right;margin-right: -15px;">
                    <input type="text" placeholder="请选择日期" name="date" id="date_input" value="{{ d_info.datetime }}" /><br/>
                    </div><br/>
                    {% if error.date %}<span class="error_tips">{{ error.date.0 }}</span>{% endif %}
                </li>
                <li><span class="assets_title">备注:</span>
                    <textarea name="info" >{{ d_info.info }}</textarea>
                </li>
            </ul>
        {% endif %}
        </div>
        <input id="edit_btn" value="保存" type="submit"  />
        <a href="{% url 'domain' %}"><div class="return_btn" >返回</div></a>
        {% csrf_token %}
    </form>
    </div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% block title %}错误{% endblock %}
{% block maincontent %}
    <div class="title">所在位置/错误页</div>
    <div class="error_wrapper">
        别瞎点！<a href="{% url 'server' %}" onClick="javascript :history.back(-1);">返回首页</a>
    </div>
{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</head>
<body style="background: #f7f7f7">
<!-- 内容区 -->
	<div class="loginewrapper_div">
		<span>同道<br />运维管理平台</span>
        <form action="{% url 'login' %}" method="post" >
            <div class="login_div">
                用户名：<input type="text" name="username" value="{{ login_form.username.value }}" placeholder="请输入用户名" /> <br />
                密&nbsp;&nbsp;&nbsp;码：<input type="password" name="password" value="{{ login_form.password.value }}" placeholder="请输入密码" /> <br />
                {% if err %}<b>{{ err }}</b>{% endif %}
                <input class="loginbtn" type="submit" value="登录" />
                <input class="loginbtn can" disabled="hidden" type="button" value="注册" />
            </div>
            {% csrf_token %}
        </form>
	</div>
</body>
</html>

templates/server-detail.html
{% extends 'base.html' %}
{% block title %}
服务器详情页
{% endblock %}
{% block maincontent %}
    <div class="title">所在位置/服务器详情</div>
    <div class="detail_wrapper">
				<!-- 资产详情页 -->
					<div class="left">
						<ul class="list-unstyled">
							<li><span class="assets_title">主机名:</span>{{ server.hostname }}</li>
							<li><span class="assets_title">远程ip:</span>{{ server.remote_ip }}</li>
							<li><span class="assets_title">端口:</span>{{ server.port }}</li>
							<li><span class="assets_title">所属机房:</span>{{ server.idc }}</li>
							<li><span class="assets_title">所属业务:</span>{{ server.team }}</li>
							<li><span class="assets_title">所属账号:</span>{{ server.account }}</li>
							<li><span class="assets_title">连接用户:</span>{{ server.username }}</li>
							<li><span class="assets_title">连接密码:</span>{{ server.password }}</li>
							<li><span class="assets_title">价格:</span>{{ server.price }}元</li>
							<li><span class="assets_title">所属环境:</span>{{ server.get_env_status_display }}</li>
							<li><span class="assets_title">到期时间:</span>{{ server.get_deadtime_display }}</li>
							<li><span class="assets_title">备注:</span>{{ server.info }}</li>
						</ul>
					</div>
					<div class="right">
						<ul class="list-unstyled">
							<li><span class="assets_title">更新状态:</span>{{ server.get_update_status_display }}</li>
							<li><span class="assets_title">主机IP:</span>{{ server.self_ip }}</li>
							<li><span class="assets_title">系统版本:</span>{{ server.assets.release }}</li>
							<li><span class="assets_title">内核信息:</span>{{ server.assets.kernel_version }}</li>
							<li><span class="assets_title">CPU型号:</span>{{ server.assets.cpu_type }}</li>
							<li><span class="assets_title">CPU个数:</span>{{ server.assets.cpu_nums }}</li>
							<li><span class="assets_title">内存:</span>{{ server.assets.mem }}</li>
							<li><span class="assets_title">SWAP:</span>{{ server.assets.swap }}</li>
                            {% for disk in server.disk_info.all %}
							    <li><span class="assets_title">硬盘:</span>{{ disk.name }} -- {{ disk.size }}</li>
                            {% endfor %}
						</ul>
					</div>
					<a href="{% url 'server-edit' server.id %}"><div class="return_btn edit_btn">编辑</div></a>
                    <a href="{% url 'server' %}"><div class="return_btn" >返回</div></a>
				<div class="secert_info"><span class="assets_title" style="float: left;">密码信息:</span>
					<div class="secert_info_box">&nbsp;{{ server.info_sercret }}
					</div>
				</div>

			</div>
{% endblock %}

templates/server.html
{% extends 'base.html' %}
{% block title %}
服务器首页
{% endblock %}
{% block maincontent %}
    {% if tips %}
        <div class="notice_tips">{{ tips }}</div>
        {% block extra_js %}
            <script type="text/javascript">
                $(document).ready(function(){
                    t = setTimeout(function () {
                        $('.notice_tips').slideUp('slow');

                    },1500);
                    //location.href = "/server/";
                    //clearTimeout(t);
                })
            </script>
        {% endblock %}
    {% endif %}
    <div class="title">所在位置/服务器首页</div>
    <div class="search_wrapper">
        <!-- 搜索框 -->
        <form action="{% url 'server' %}" method="get">
            <div class="search">
                <select name="category">
                    <option value="0" >所有业务线</option>
                    {% for t in team %}
                        <option {% ifequal category t.id|escape  %}selected{% endifequal %} value="{{ t.id }}">{{ t.name }}</option>
                    {% endfor %}
                </select>
                <input type="text" name="keyword" {% ifnotequal keyword "" %}value="{{ keyword }}"{% endifnotequal %} placeholder="请输入搜索关键字" />
                <input type="submit" id="searchbtn" value="搜 索" />
                <a href="{% url 'add-server' %}"><input type="button" id="addbtn" value="添 加" /></a>
            </div>
        </form>
    </div>
    <!-- 数据表格 -->
    <div class="table_wrapper">
        <table class="table table-bordered table-hover">
            <thead>
                <tr><td width="50px">序号</td><td>主机名</td><td>连接IP</td><td>端口</td><td>主机IP</td><td>所属部门</td><td>所属环境</td><td width="120px;">操作</td></tr>
            </thead>
            <tbody>
                {% for s in all_server.object_list %}
                <tr><td>{{ forloop.counter }}</td><td>{{ s.hostname }}</td><td>{{ s.remote_ip }}</td><td>{{ s.port }}</td>
                <td>{{ s.self_ip }}</td><td>{{ s.team }}</td><td>{{ s.get_env_status_display }}</td>
                <td><a href="{% url 'server-detail' s.id %}">查看</a> | <a href="{% url 'server-edit' s.id %}">编辑</a></td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <input type="button" id="update_data" class="btn btn-success" value="更新数据" />
    &nbsp;&nbsp;&nbsp;&nbsp;共计 <b style="color: #d9534f">{{ count }}</b> 条数据。
    <!-- 页码 -->
    <div class="Page navigation mypage">
    <ul class="pagination">
        {% if all_server.has_previous %}
            <li><a href="?{{ all_server.previous_page_number.querystring }}">&lsaquo;&lsaquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#">&lsaquo;&lsaquo;</a></li>
        {% endif %}
        {% for page in all_server.pages %}
            {% if page %}
                {% ifequal page all_server.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page  }}</a></li>
                {% else %}
                    <li><a href="?{{ page.querystring }}">{{ page  }}</a></li>
                {% endifequal %}
            {% else %}
                <li><a href="#" class="none">...</a></li>
            {% endif %}
        {% endfor %}
        {% if all_server.has_next %}
            <li><a href="?{{ all_server.next_page_number.querystring }}">&rsaquo;&rsaquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#">&rsaquo;&rsaquo;</a></li>
        {% endif %}
    </ul>
    </div>
    <script>
    $('#update_data').on('click',function () {
        $('#update_data').val("更新中...");
        $.ajax({
            url: '{% url "update_data" %}',
            type: "GET",
            success: function (arg) {
                $('#update_data').val(arg);
            }
        })
    })
    </script>
{% endblock %}